export const listCountrys = [
    "Argentina", 
  "Australia",
  "Bolivia",
  "Brazil" ,
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Cuba" ,
  "Ecuador", 
  "Egypt",
  "India" ,
  "Italy" ,
  "Japan",
  "Mexico",
  "Peru",
  "Russia",
  "Ukraine",
  "Uruguay ",
  "Venezuela",
  "Belgium ",
  "Denmark ",
  "Germany" ,
  "Iceland" ,
  "Ireland ",
  "Ivory Coast ",
  "Latvia" ,
  "Morocco" ,
  "Netherlands",
  "Norway ",
  "Saudi Arabia", 
  "South Africa" ,
  "Spain",
  "Sweden", 
  "United Arab Emirates",
  "United Kingdom",
  "United States of America"
   ]